### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by kurtrisser** [Pask423/keycloak-springboot-article#3]
When I try to access http://localhost:8080/hello, I get an error page:

This page isn’t working
localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

Do you have any idea how to fix this?  I did clear the cookies but to no avail.
Thanks.

**Comment by Pask423** [comment]
I will try my best, but could you tell me how you run your app ?
Maybe try to pull new changes because I forget to remove abs path from one of the scripts.
