### ISSUE TITLE
Boot 3.1 Deprecates HttpSecurity methods in GlobalSecurityConfiguration

### ISSUE THREAD

**Issue by cobar79** [Pask423/keycloak-springboot-article#4]
Just curious if you have an update for boot 3.1/spring 6.1 since spring 6.1 deprecated

HttpSecurity auhtorizeHttpRequests, oauth2ResourceServer and sessionManagement methods?

Disregard. I found the method in the HttpSecurity bean

**Comment by Pask423** [comment]
Hi sorry it took me so long.
Just fixed and replaced with current recommended approach
